import { Footer, FooterProps } from "ui";
import { BeakerIcon } from "@heroicons/react/24/solid";
import Head from "next/head";

const footerProps: FooterProps = {
  logo: <div>Logo</div>,
  socialLinks: [
    {
      text: "Twitter",
      href: "https://twitter.com",
      icon: <BeakerIcon />,
    },
    {
      text: "Twitter",
      href: "https://twitter.com",
      icon: <BeakerIcon />,
    },
    {
      text: "Twitter",
      href: "https://twitter.com",
      icon: <BeakerIcon />,
    },
    {
      text: "Twitter",
      href: "https://twitter.com",
      icon: <BeakerIcon />,
    },
  ],
  rows: [
    {
      title: "Row 1",
      links: [
        {
          text: "Link 1",
          href: "#",
        },
        {
          text: "Link 2",
          href: "#",
        },
      ],
    },
    {
      title: "Row 3",
      links: [
        {
          text: "Link 1",
          href: "#",
        },
        {
          text: "Link 2",
          href: "#",
        },
      ],
    },
    {
      title: "Row 4",
      links: [
        {
          text: "Link 1",
          href: "#",
        },
        {
          text: "Link 2",
          href: "#",
        },
      ],
    },
    {
      title: "Row 5",
      links: [
        {
          text: "Link 1",
          href: "#",
        },
        {
          text: "Link 2",
          href: "#",
        },
      ],
    },
  ],
  copyRight:
    "Copyright © 2022- imbalol. imbalol isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties. Riot Games, and all associated properties are trademarks or registered trademarks of Riot Games, Inc.",
};

export const DefaultLayout = ({ children }: React.PropsWithChildren) => (
  <>
    <Head>
      <title>imba lol</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="flex flex-col h-screen">
      <main className="container mx-auto max-w-screen-xl flex flex-1 flex-col gap-2">{children}</main>
      <div className="shrink mt-4">
        <Footer {...footerProps} />
      </div>
    </div>
  </>
);
