name: Ekko CI

on:
  push:
    paths:
      - "services/ekko/**"
  pull_request:
    paths:
      - "services/ekko/**"

jobs:
  one-line:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
