name: Hello world

on:
  workflow_call:
    inputs:
      foo:
        type: string
        required: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: LOL
        run: echo "hello world ${{ inputs.foo }}"
