name: Playwright Tests
on:
  workflow_call:
    inputs:
      project:
        required: false
        type: string

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright Browsers
        run: pnpm dlx playwright i --with-deps
      - name: Run Playwright tests
        run: pnpm test:e2e --filter ${{ inputs.scope }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
